openapi: 3.0.0
info:
  title: EnFlex.IT - Dynamic Content Api
  description: This is the Definition of the Api to dynamically fetch content for any enflex.it application
  contact:
    name: EnFlex.IT
    url: https://www.enflex.it
    email: admin@enflex.it
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0

servers:
  - url: http://localhost:8080
  - url: https://www.enflex.it

# --- Api-Paths -------------------------------------------
paths:

  /menu:
    post:
      summary: Create a new menu
      description: Creates a new menu and saves it in the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MenuItem'
      responses:
        "201":
          description: Menu created
          content:
            application/json:
              schema:
                type: object
                properties:
                  menuID:
                    type: integer
        "400":
          description: Invalid request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "503":
          description: Service unavailable  
          
    get:
      summary: Enables to build-up the menu structure
      description: Returns the menu structure available for the current user
      parameters:
        - name: lang
          in: query
          description: the language locale to use
          style: simple
          schema:
            type: string
      responses: 
        "200":
          $ref: "#/components/responses/MenuArray"
        "401":
            description: Unauthorized
        "503":
            description: Service unavailable
    
  /menu/{menuID}:  
    put:
      summary: Enables to update a menu
      parameters:
        - name: menuID
          in: path
          required: true
          description: The unique ID of the menu to be updated
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MenuItem'
      responses:
        "200":
          description: The menu was updated!
        "400":
          description: Invalid request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "503":
          description: Service unavailable
  
    delete:
      summary: Deletes the specified menu
      description: Removes the menu, its submenus and all associated menu-content assignments from the database.
      parameters:
        - name: menuID
          in: path
          required: true
          description: The unique ID of the menu to be deleted
          schema:
            type: integer
      responses:
        "200":
          description: The menu was deleted
        "400":
          description: Invalid request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "503":
          description: Service unavailable

  /menu/{menuID}/contentElement/{elementID}:
    put:
      summary: Add the specified content element to the specified menu
      
      parameters:
        - name: menuID
          in: path
          required: true
          description: The unique ID of the menu
          schema:
            type: integer
        - name: elementID
          in: path
          required: true
          description: The unique ID of the content element
          schema:
            type: integer
      responses:
        "200":
          description: Content element was added to the menu
        "400":
          description: Invalid request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "503":
          description: Service unavailable
          
  /menu/{menuID}/permissions:
    put:
      summary: Enables to set the required rights to access the specified menu
      parameters:
        - name: menuID
          in: path
          required: true
          description: The unique ID of the menu
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        "200":
          description: The right was set
        "400":
          description: Invalid request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "503":
          description: Service unavailable

  /contentElement/:
    post:
      summary: Create new content
      description: Creates a new content element
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateContentRequest'
      responses:
        "201":
          description: Content created
          content:
            application/json:
              schema:
                type: object
                properties:
                  elementID:
                    type: integer
        "400":
          description: Invalid request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "503":
          description: Service unavailable      
    
  /content/{menuID}:
    get:
      summary: Returns the content for the specified ID
      description: Returns the list of content elements for the specified menu ID.
      parameters:
      - name: menuID
        in: path
        description: numeric ID of the content
        required: true
        schema:
          type: integer
      responses:
        "200":
          $ref: '#/components/responses/ContentArray'
        "400":
          description: Invalid request
        "401":
          description: Unauthorized
        "503":
          description: Service unavailable      

  /contentElement/{elementID}:
    get:
      summary: Returns the content element for the specified ID
      description: Returns the single content element corresponding to the specified ID.
      parameters:
      - name: elementID
        in: path
        description: unique ID of the content element
        required: true
        schema:
          type: integer
      responses:
        "200":
          $ref: "#/components/responses/ContentElement"
        "400":
          description: Invalid request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "503":
          description: Service unavailable

    put:
      summary: Enables to update content elements
      parameters:
        - name: elementID
          in: path
          required: true
          description: The unique ID of the content element to update
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AbstractSiteContent' 
      responses:
        "200":
          description: The element was updated!
        "400":
          description: Invalid request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "503":
          description: Service unavailable

    delete:
      summary: Deletes the specified content element
      description: Removes the content element from the database and thus from all asociated menus.
      parameters:
        - name: elementID
          in: path
          required: true
          description: The unique ID of the content element to delete
          schema:
            type: integer
      responses:
        "200":
          description: The content element was deleted
        "400":
          description: Invalid request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "503":
          description: Service unavailable

# ---------------------------------------------------------
# --- Components  -----------------------------------------
# ---------------------------------------------------------
components:

  # -------------------------------------------------------
  # --- Responses -----------------------------------------
  responses:

    MenuArray:
      description: The menus to be seen by the current user
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MenuList'

    ContentArray:
      description: List of content elements
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SiteContentList'

    ContentElement:
      description: A single content element
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AbstractSiteContent'
      
  # -------------------------------------------------------
  # --- Schemas & type definition -------------------------
  schemas:

    MenuList:
      type: object
      properties:
        menuList:
          type: array
          items:
            $ref: '#/components/schemas/MenuItem'

    MenuItem:
      type: object
      properties:
        menuID:
          type: integer
        parentID:
          type: integer
        isHeadMenu:
          type: boolean
        position:
          type: integer
        caption:
          type: string
        pathID:
          type: string
        pathCaption:
          type: string
        pathPosition:
          type: string
      required:
       - ID
       - position
       - isHeadMenu
       - caption

    CreateContentRequest:
      type: object
      properties:
        menuID:
          type: integer

        position:
          type: integer

        content:
          $ref: '#/components/schemas/AbstractSiteContent'

      required:
        - menuID
        - position
        - content
  
    SiteContentList:
      type: object
      properties:
        contentList:
          type: array
          items:
            $ref: '#/components/schemas/AbstractSiteContent'
      required:
        - "contentList"

    AbstractSiteContent:
      type: object
      properties:
        uniqueContentID:
          type: integer
        editable:
          type: boolean
        updatePeriodInSeconds:
          type: integer
      required:
      - editable
      - uniqueContentID
      - updatePeriodInSeconds
      discriminator:
        propertyName: AbstractSiteContentType
        mapping:
          SiteContentMedia: '#/components/schemas/SiteContentMedia'
          AbstractChart: '#/components/schemas/AbstractChart'
          SiteContentProperties: '#/components/schemas/SiteContentProperties'
          SiteContentTable: '#/components/schemas/SiteContentTable'

    SiteContentMedia:
      allOf:
        - $ref: '#/components/schemas/AbstractSiteContent'
        - type: object
          properties:
            mimeType:
              type: string
          required:
            - mimeType
          discriminator:
            propertyName: AbstractSiteContentType
            mapping:
              SiteContentText: '#/components/schemas/SiteContentText'
              SiteContentImage: '#/components/schemas/SiteContentImage'

    SiteContentText:
      allOf:
        - $ref: '#/components/schemas/SiteContentMedia'
        - type: object
          properties:
            text:
              type: string
          required:
            - text

    SiteContentImage:
      allOf:
        - $ref: '#/components/schemas/SiteContentMedia'
        - type: object
          properties:
            dataInB64:
              type: string
          required:
            - dataInB64

    # --- Schema definitions related to charts ------------
    SiteContentChart:
      allOf:
        - $ref: '#/components/schemas/AbstractSiteContent'
        - type: object
          properties:
            chart:
              $ref: '#/components/schemas/AbstractChart'    
                    
    AbstractChart:
      type: object
      properties:
        title:
          type: string
        showLegend:
          type: boolean            
        xAxisLabel:
          type: string
        yAxisLabel:
          type: string
        dataSeries:
          type: array
          items: 
            $ref: '#/components/schemas/DataSeries'
      required:
        - title
        - dataSeries       
      discriminator:
        propertyName: ChartType
        mapping:
          LineChart: '#/components/schemas/LineChart'
          TimeSeriesChart: '#/components/schemas/TimeSeriesChart'
          BarChart: '#/components/schemas/BarChart'
          PieChart: '#/components/schemas/PieChart'
          ScatterPlot: '#/components/schemas/ScatterPlot'

    LineChart:
      allOf:
        - $ref: '#/components/schemas/AbstractChart'        
        - type: object
          properties:
            secondaryYAxisLabel:
              type: string
          required:
            - xAxisLabel
            - yAxisLabel

    TimeSeriesChart:
      allOf:
        - $ref: '#/components/schemas/LineChart'
        - type: object
          properties:
            timeFormat:
              type: string
        
    BarChart:
      allOf:
        - $ref: '#/components/schemas/AbstractChart'
        - type: object
          properties:
            secondaryYAxisLabel:
              type: string
          required:
            - xAxisLabel
            - yAxisLabel
    
    PieChart:
      allOf:
        - $ref: '#/components/schemas/AbstractChart'          
        
    ScatterPlot:
      allOf:
        - $ref: '#/components/schemas/AbstractChart'
        - type: object
          properties:
            secondaryYAxisLabel:
              type: string
          required:
            - xAxisLabel
            - yAxisLabel
    
    DataSeries:
        properties: 
          label:
            type: string
          secondaryYAxis:
            type: boolean
            default: false
        discriminator:
          propertyName: xValueType
          mapping:
            DataSeriesWithValues: '#/components/schemas/DataSeriesWithValues'
            DataSeriesWithReference: '#/components/schemas/DataSeriesWithReference'
        required:
          - label


    DataSeriesWithValues:
      allOf:
        - $ref: '#/components/schemas/DataSeries'
        - type: object
          properties:
            entries:
              type: array
              items:
                $ref: '#/components/schemas/AbstractValueRow'
          required:
            - entries

    DataSeriesWithReference:
      allOf:
        - $ref: '#/components/schemas/DataSeries'
        - type: object
          properties:
            reference:
              type: string
      required:
        - reference
                          
                                  
    AbstractValueRow:
        type: object    
        properties:          
          value:
            type: array
            items:
              type: double
        discriminator:
          propertyName: xValueType
          mapping:
            Numeric: '#/components/schemas/ValueRowNumeric'
            DateTime: '#/components/schemas/ValueRowDateTime'
            Category: '#/components/schemas/ValueRowCategory'
        required:          
          - value
          - xValueType
          
    ValueRowNumeric:
      allOf:
        - $ref: '#/components/schemas/AbstractValueRow'
        - type: object
          properties:
            xValue: 
              type: number
              format: double            
          required:
            - xValue
    
    ValueRowDateTime:
      allOf:
        - $ref: '#/components/schemas/AbstractValueRow'
        - type: object
          properties:
            isoDateTime: 
              type: string      
          required:
            - isoDateTime
            
    ValueRowCategory:
      allOf:
        - $ref: '#/components/schemas/AbstractValueRow'
        - type: object
          properties:
            category: 
              type: string
          required:
            - xValue

    # --- Schema definitions related to properties --------
    SiteContentProperties:
      allOf:
        - $ref: '#/components/schemas/AbstractSiteContent'
        - type: object
          properties:
            propertyEntries:
              type: array
              items: 
                $ref: '#/components/schemas/PropertyEntry'
          required:
            - propertyEntries

    PropertyEntry:
      properties:
        key:
          type: string
        value:
          type: string
        valueType:
          $ref: '#/components/schemas/ValueType'
      required:
        - key
        - value
        - valueType

    ValueType:
      type: string
      enum:
      - INTEGER
      - BOOLEAN
      - STRING
      - LONG
      - DOUBLE

    # --- Schema definitions related to tables ------------
    SiteContentTable:
      allOf:
        - $ref: '#/components/schemas/AbstractSiteContent'
        - type: object
          properties:
            header:
              type: array
              items:
                type: string
            dataType:
              type: array
              items:
                $ref: '#/components/schemas/ValueType'
            data:
              type: array
              items:
                $ref: '#/components/schemas/RowVector'
          required:
            - data
            - dataType
            - header

    RowVector:
      type: array
      items:
        type: string
