openapi: 3.0.0
info:
  title: EnFlex.IT - Dynamic Content Api
  description: This is the Definition of the Api to dynamically fetch content for any enflex.it application
  contact:
    name: EnFlex.IT
    url: https://www.enflex.it
    email: admin@enflex.it
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0

servers:
  - url: http://localhost:8080
  - url: https://www.enflex.it

# --- Api-Paths -------------------------------------------
paths:
  /menu/:
    get:
      summary: Enables to build-up the menu structure
      description: Returns the menu structure available for the current user
      responses: 
        "202":
          $ref: "#/components/responses/MenuArray"

  /content/{menuID}:
    get:
      summary: Returns the content for the specified ID
      description: |
        Returns content information.
      parameters:
      - name: menuID
        in: path
        description: numeric ID of the content
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          $ref: '#/components/responses/ContentArray'

  /content/:
    put:
      summary: Enables to update content
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/SiteContentListUpdate' 
      responses:
        "201":
          description: Content was updated!

# ---------------------------------------------------------
# --- Components  -----------------------------------------
# ---------------------------------------------------------
components:

  # -------------------------------------------------------
  # --- Responses -----------------------------------------
  responses:

    MenuArray:
      description: The menus to be seen by the current user
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MenuList'

    ContentArray:
      description: Success - Content
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SiteContentList'

  # -------------------------------------------------------
  # --- Schemas & type definition -------------------------
  schemas:

    MenuList:
      type: object
      properties:
        menuList:
          type: array
          items:
            $ref: '#/components/schemas/MenuItem'

    MenuItem:
      type: object
      properties:
        menuID:
          type: integer
        parentID:
          type: integer
        isHeadMenu:
          type: boolean
        position:
          type: integer
        caption:
          type: string
        pathID:
          type: string
        pathCaption:
          type: string
        pathPosition:
          type: string
      required:
       - ID
       - position
       - isHeadMenu
       - caption

    SiteContentListUpdate:
      type: object
      properties:
        menuID:
          type: integer
        contentList:
          type: array
          items:
            $ref: '#/components/schemas/AbstractSiteContent'
          maxItems: 100
  
    SiteContentList:
      type: object
      properties:
        contentList:
          type: array
          items:
            $ref: '#/components/schemas/AbstractSiteContent'
      required:
        - "contentList"

    AbstractSiteContent:
      type: object
      properties:
        uniqueContentID:
          type: integer
        editable:
          type: boolean
        updatePeriodInSeconds:
          type: integer
      required:
      - editable
      - uniqueContentID
      - updatePeriodInSeconds
      discriminator:
        propertyName: AbstractSiteContentType
        mapping:
          SiteContentMedia: '#/components/schemas/SiteContentMedia'
          AbstractSiteContentChart: '#/components/schemas/AbstractSiteContentChart'
          SiteContentProperties: '#/components/schemas/SiteContentProperties'
          SiteContentTable: '#/components/schemas/SiteContentTable'

    SiteContentMedia:
      allOf:
        - $ref: '#/components/schemas/AbstractSiteContent'
        - type: object
          properties:
            mimeType:
              type: string
          required:
            - mimeType
          discriminator:
            propertyName: AbstractSiteContentType
            mapping:
              SiteContentText: '#/components/schemas/SiteContentText'
              SiteContentImage: '#/components/schemas/SiteContentImage'

    SiteContentText:
      allOf:
        - $ref: '#/components/schemas/SiteContentMedia'
        - type: object
          properties:
            text:
              type: string
          required:
            - text

    SiteContentImage:
      allOf:
        - $ref: '#/components/schemas/SiteContentMedia'
        - type: object
          properties:
            dataInB64:
              type: string
          required:
            - dataInB64

    # --- Schema definitions related to charts ------------
    AbstractSiteContentChart:
      allOf:
        - $ref: '#/components/schemas/AbstractSiteContent'
        - type: object
          properties:
            title:
              type: string
            showLegend:
              type: boolean            
            xAxisLabel:
              type: string
            yAxisLabel:
              type: string
            dataSeries:
              type: array
              items: 
                $ref: '#/components/schemas/DataSeries'
          required:
            - title
            - dataSeries       
          discriminator:
            propertyName: AbstractSiteContentType
            mapping:
              SiteContentLineChart: '#/components/schemas/SiteContentLineChart'
              SiteContentTimeSeriesChart: '#/components/schemas/SiteContentTimeSeriesChart'
              SiteContentBarChart: '#/components/schemas/SiteContentBarChart'
              SiteContentPieChart: '#/components/schemas/SiteContentPieChart'
              SiteContentScatterPlot: '#/components/schemas/SiteContentScatterPlot'

    SiteContentLineChart:
      allOf:
        - $ref: '#/components/schemas/AbstractSiteContentChart'        
        - type: object
          properties:
            secondaryYAxisLabel:
              type: string
          required:
            - xAxisLabel
            - yAxisLabel

    SiteContentTimeSeriesChart:
      allOf:
        - $ref: '#/components/schemas/SiteContentLineChart'
        - type: object
          properties:
            timeFormat:
              type: string
        
    SiteContentBarChart:
      allOf:
        - $ref: '#/components/schemas/AbstractSiteContentChart'
          required:
            - xAxisLabel
            - yAxisLabel
    
    SiteContentPieChart:
      allOf:
        - $ref: '#/components/schemas/AbstractSiteContentChart'          
        
    SiteContentScatterPlot:
      allOf:
        - $ref: '#/components/schemas/AbstractSiteContentChart'
          required:
            - xAxisLabel
            - yAxisLabel
    
    DataSeries:
        properties:
          label:
            type: string
          secondaryYAxis:
            type: boolean
            default: false
          entries:
            type: array
            items:
              $ref: '#/components/schemas/AbstractValuePair'
        required:
          - label
          - entries
            
    AbstractValuePair:
        type: object    
        properties:          
          value:
            type: number
            format: double
        discriminator:
          propertyName: xValueType
          mapping:
            Numeric: '#/components/schemas/ValuePairNumeric'
            DateTime: '#/components/schemas/ValuePairDateTime'
            Category: '#/components/schemas/ValuePairCategory'
        required:          
          - value
          - xValueType
          
    ValuePairNumeric:
      allOf:
        - $ref: '#/components/schemas/AbstractValuePair'
        - type: object
          properties:
            xValue: 
              type: number
              format: double            
          required:
            - xValue
    
    ValuePairDateTime:
      allOf:
        - $ref: '#/components/schemas/AbstractValuePair'
        - type: object
          properties:
            isoDateTime: 
              type: string      
          required:
            - isoDateTime
            
    ValuePairCategory:
      allOf:
        - $ref: '#/components/schemas/AbstractValuePair'
        - type: object
          properties:
            category: 
              type: string
          required:
            - xValue

    # --- Schema definitions related to properties --------
    SiteContentProperties:
      allOf:
        - $ref: '#/components/schemas/AbstractSiteContent'
        - type: object
          properties:
            propertyEntries:
              type: array
              items: 
                $ref: '#/components/schemas/PropertyEntry'
          required:
            - propertyEntries

    PropertyEntry:
      properties:
        key:
          type: string
        value:
          type: string
        valueType:
          $ref: '#/components/schemas/ValueType'
      required:
        - key
        - value
        - valueType

    ValueType:
      type: string
      enum:
      - INTEGER
      - BOOLEAN
      - STRING
      - LONG
      - DOUBLE

    # --- Schema definitions related to tables ------------
    SiteContentTable:
      allOf:
        - $ref: '#/components/schemas/AbstractSiteContent'
        - type: object
          properties:
            header:
              type: array
              items:
                type: string
            dataType:
              type: array
              items:
                $ref: '#/components/schemas/ValueType'
            data:
              type: array
              items:
                $ref: '#/components/schemas/RowVector'
          required:
            - data
            - dataType
            - header

    RowVector:
      type: array
      items:
        type: string
