openapi: 3.1.0
# General Information
info:
  title: Enflex.IT General API
  description: This is the common REST-API for all Enflex.IT Applications.
  contact:
    name: EnFlex.IT
    url: https://www.enflex.it
    email: admin@enflex.it
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
# Security
security:
# Tags to classifiy / organize paths
tags:
# The paths of a REST-API
paths:
